# Generated by Django 4.2.1 on 2023-05-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precio_venta', models.DecimalField(decimal_places=3, max_digits=3, max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'nombre de los articulos',
                'verbose_name_plural': 'articulos',
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=40)),
                ('serie_comprobante', models.CharField(max_length=30)),
                ('num_comprobante', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('impuesto', models.DecimalField(decimal_places=3, max_digits=10, max_length=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10, max_length=10)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'total de ingresos',
                'verbose_name_plural': 'ingresos',
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('num_documento', models.IntegerField(default=0)),
                ('cuit', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('id_ingreso', models.ManyToManyField(to='gestionVentas.ingreso')),
            ],
            options={
                'verbose_name': 'registro de las personas',
                'verbose_name_plural': 'personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=40)),
                ('documento', models.CharField(max_length=10)),
                ('numero_documento', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'categorias de usuarios',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=30)),
                ('serie_comprobante', models.CharField(max_length=20)),
                ('num_comprobante', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('impuesto', models.DecimalField(decimal_places=3, max_digits=10, max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('id_persona', models.ManyToManyField(to='gestionVentas.persona')),
                ('id_usuario', models.ManyToManyField(to='gestionVentas.usuario')),
            ],
            options={
                'verbose_name': 'cantidad de ventas',
                'verbose_name_plural': 'ventas',
                'db_table': 'venta',
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVentas.usuario'),
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id_detalleventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10, max_length=10)),
                ('descuento', models.DecimalField(decimal_places=3, max_digits=10, max_length=10)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVentas.articulo')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVentas.venta')),
            ],
            options={
                'verbose_name': 'cantidad de ventas',
                'verbose_name_plural': 'detalle de ventas',
                'db_table': 'detalle de venta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_ingreso',
            fields=[
                ('id_detalleingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10, max_length=10)),
                ('codigo', models.ManyToManyField(to='gestionVentas.articulo')),
                ('id_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVentas.ingreso')),
            ],
            options={
                'verbose_name': 'cantidad de ingresos',
                'verbose_name_plural': 'detalles de los ingresos',
                'db_table': 'detalle del ingreso',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=20)),
                ('codigo', models.ManyToManyField(to='gestionVentas.articulo')),
            ],
            options={
                'verbose_name': 'nombre de las categorias',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_categoria',
            field=models.ManyToManyField(to='gestionVentas.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_detalleingreso',
            field=models.ManyToManyField(to='gestionVentas.detalle_ingreso'),
        ),
    ]
